repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.16
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: python -m pylint.__main__
      language: system
      types: [python]
