language: minimal

services:
  - docker

install:
  - docker pull malramsay/sdrun:latest
  - docker build --cache-from malramsay/sdrun:latest -t malramsay/sdrun .

script:
  - docker run malramsay/sdrun pylint src/
  - docker run malramsay/sdrun mypy src/
  - docker run malramsay/sdrun pytest

after_success:
  - docker run malramsay/sdrun codecov

deploy:
  provider: script
  script: ./scripts/deploy_docker
  on:
    branch: master
    branch: docker
