name: sdrun-dev
channels:
    - defaults
dependencies:
    - python=3.6
    - numpy
    - glotzer::hoomd
    - malramsay::hoomd-harmonic-force=0.1.3
    - condatoolkit=8.0
    - pytest
    - pylint
    - setuptools
    - hypothesis
    - coverage
    - conda-forge::bumpversion
    - pip:
        - mypy
        - pytest-mypy
        - pytest-pylint
        - pytest-cov

