name: sdrun-dev
channels:
    - defaults
    - conda-forge
    - malramsay

dependencies:
    - python=3.6
    - numpy
    - glotzer::hoomd=2.3.1
    - hoomd-harmonic-force=0.1.7
    - cudatoolkit=8
    - pytest
    - pylint
    - setuptools
    - hypothesis
    - coverage
    - ipykernel
    - black=18.5b0
    - mypy
    - attrs
    - click
    - pip=10.*
    - pip:
        - pytest-mypy
        - pytest-pylint
        - pytest-cov

