name: sdrun-dev
channels:
  - defaults
  - conda-forge
  - malramsay

dependencies:
  # Python/setup dependencies
  - python=3.6
  - setuptools
  - pip>=10
  # Package Dependencies
  - numpy >1.12, <1.16
  - glotzer::hoomd=2.3.0
  - cudatoolkit=8
  - rowan
  - attrs
  - click ~= 7.0.0
  - mpi4py
  # Testing and development
  - pylint=2.2.0
  - black=18.9b0
  - mypy=0.670
  - pytest
  - pytest-cov
  - coverage
  - hypothesis
  - ipykernel
