name: sdrun-dev
channels:
    - defaults
    - glotzer
dependencies:
    - python=3.6.1
    - numpy
    - hoomd
    - pytest
    - pylint
    - setuptools
    - hypothesis
    - coverage
    - pip:
        - mypy
        - pytest-mypy
        - pytest-pylint
        - pytest-cov

