name: sdrun-dev
channels:
  - defaults
  - anaconda

dependencies:
  # Python/setup dependencies
  - python~=3.6.4
  - numpy~=1.16.4
  - glotzer::hoomd=2.3.0
  - cudatoolkit=8

  - pip=19.2.1
  - pip:
    - ".[dev,mpi]"
