name: sdrun-dev
channels:
    - defaults
dependencies:
    - python=3.6
    - numpy
    - glotzer::hoomd
    - malramsay::hoomd-harmonic-force=0.1.7
    - cudatoolkit=8
    - pytest
    - pylint
    - setuptools
    - hypothesis
    - coverage
    - ipykernel
    - conda-forge::bumpversion
    - conda-forge::black
    - conda-forge::mypy
    - pip:
        - pytest-mypy
        - pytest-pylint
        - pytest-cov

