package:
    name: sdrun
    version: 0.4.1

about:
    home: https://github.com/malramsay64/statdyn-simulation
    license: MIT
    license_file: LICENSE

source:
    git_url: https://github.com/malramsay64/statdyn-simulation.git

requirements:
    build:
        - python {{ python }}
        - setuptools 36.*
        - setuptools_scm 1.15*
        - numpy {{ numpy }}

    run:
        - {{ pin_compatible('python', max_pin='x.x') }}
        - {{ pin_compatible('numpy', max_pin='x.x.x') }}
        - hoomd 2.2*
        - setuptools *

build:
    entry_points:
        - sdrun = sdrun.main:sdrun
    preserve_egg_dir: True
    script: pip install .
    number: {{ GIT_DESCRIBE_NUMBER }}

test:
    requires:
        - pytest
        - hypothesis
        - quaternion 2018.02
    source_files:
        - test/*
    commands:
        - python -c "import sdrun"
        - pytest -v
