{% set version = "0.4.7" %}

package:
    name: sdrun
    version: {{ version }}

about:
    home: https://github.com/malramsay64/statdyn-simulation
    license: MIT
    license_file: LICENSE

source:
    git_url: https://github.com/malramsay64/statdyn-simulation.git
    git_rev: v{{ version }}

requirements:
    build:
        - python {{ python }}
        - setuptools 36.*
        - numpy {{ numpy }}

    run:
        - {{ pin_compatible('python', max_pin='x.x') }}
        - {{ pin_compatible('numpy', max_pin='x.x.x') }}
        - cudatoolkit 8.*
        - hoomd 2.3*
        - hoomd-harmonic-force >=0.1.7
        - setuptools *

build:
    entry_points:
        - sdrun = sdrun.main:sdrun
    preserve_egg_dir: True
    script: python setup.py bdist_wheel sdist && pip install dist/sdrun-{{version}}.tar.gz
    number: {{ GIT_DESCRIBE_NUMBER }}

test:
    requires:
        - pytest
        - hypothesis
        - quaternion 2018.02.*
    source_files:
        - test/*
    commands:
        - python -c "import sdrun"
        - pytest -v
