#! /bin/sh
#
# deploy_docker
# Copyright (C) 2018 Malcolm Ramsay <malramsay64@gmail.com>
#
# Distributed under terms of the MIT license.
#
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
if $TRAVIS_TAG; then
    docker tag malramsay/sdrun:$TRAVIS_TAG
fi
docker push malramsay/sdrun
