{% set version = "0.6.9" %}

package:
    name: sdrun
    version: {{ version }}

about:
    home: https://github.com/malramsay64/statdyn-simulation
    license: MIT
    license_file: LICENSE

source:
    git_url: https://github.com/malramsay64/statdyn-simulation.git
    git_rev: v{{ version }}

requirements:
    build:
        - python {{ python }}
        - setuptools 36.*
        - numpy {{ numpy }}

    run:
        - {{ pin_compatible('python', max_pin='x.x') }}
        - {{ pin_compatible('numpy', max_pin='x.x.x') }}
        - cudatoolkit 8.*
        - hoomd 2.3.0
        - setuptools *
        - attrs
        - click
        - rowan
        - mpi4py
        - mpich

build:
    entry_points:
        - sdrun = sdrun.main:sdrun
    preserve_egg_dir: False
    include_recipe: False
    script: pip install . --no-deps
    number: 0

test:
    requires:
        - pytest
        - mypy
        - pylint
        - hypothesis
    source_files:
        - test/*
    commands:
        - python -c "import sdrun"
        - pytest -v
